export const users = [
  { full_name: 'Alice Johnson', username: 'alicej', email: 'alice@digishop.com', password: '123456abc', birthday: '1995-01-01' },
  { full_name: 'An Dao Thi Ha', username: 'anan', email: 'daothihaan@gmail.com', password: 'haan2004', birthday: '2004-10-01' },
  { full_name: 'Bob Smith', username: 'bobsmith', email: 'bob@digishop.com', password: 'pass1234', birthday: '1990-05-15' },
  { full_name: 'Charlie Brown', username: 'charliebrown', email: 'charlie@digishop.com', password: 'abc123', birthday: '1992-09-20' },
  { full_name: 'Diana Prince', username: 'dianaprince', email: 'diana@digishop.com', password: 'wonderwoman123', birthday: '1988-03-12' },
  { full_name: 'Ethan Hunt', username: 'admin', email: 'admin@digishop.com', password: 'admin123', is_admin: true, birthday: '01-01-1900' },
];

export const categories = [
  { name: 'Gaming Accounts' },
  { name: 'Software Licenses' },
  { name: 'VPN Services' },
  { name: 'Cloud Storage' },
  { name: 'E-Learning Platforms' },
  { name: 'Design Tools' },
  { name: 'Productivity Apps' },
  { name: 'Music' },
  { name: 'Streaming' },
];

export const products = [
  { 
    name: 'Netflix Premium', 
    category_name: 'Streaming', 
    image_url: '/products/netflix.webp',
    info: 'This is a shared, pre-activated account for the Netflix Premium plan, allowing UHD streaming. The account is accessed by multiple users, each assigned a specific profile.\nThe latest features like Games and extra member slots are not supported.\nCustomers must not change account email, password, or profile PIN/name, as this will violate the shared usage policy. The seller reserves the right to deny warranty if the policy is violated.',
    order_fulfillment: 'This is a pre-created Netflix Premium shared account (1-month) used with other customers.\nAfter completing your purchase, you will instantly receive the account login details (Email, Password, Profile Name, and PIN) via a retrieval link.\nLogin details are provided directly within your order page.\nEach customer is assigned a dedicated profile and can use the shared account on one device at a time.',
    warranty_period: 'Same as your selected package (e.g., 1-month, 3-month).',
    warranty_method: 'Replacement with an equivalent product or a refund based on the unused remaining time.\n\nWarranty Conditions:\n- Full refund within 7 days if the issue cannot be resolved.\n- After 7 days: Refund based on the unused remaining period. (Example: For a 30-day plan, if an issue occurs after 10 days of use, you receive a 66% refund of the order value.)\n\nWarranty Will Not Apply In The Following Cases:\n- The customer cancels the subscription or deletes a profile.\n- The customer attempts to modify the account email, password, or billing information.\n- The customer uses the account in a way that violates Netflix\'s Terms of Service, including downloading or unauthorized sharing of content.',
  },
  { 
    name: 'Disney+ Account', 
    category_name: 'Streaming', 
    image_url: '/products/disneyplus.jpeg',
    info: 'This is a shared account for the highest Disney+ plan available, featuring 4K streaming and simultaneous viewing, subject to shared usage rules.\nEach user is assigned a designated profile to manage their viewing history.\nModifying the account\'s primary details (email, password) is strictly prohibited and will void the warranty. Only one active stream is permitted per customer.',
    order_fulfillment: 'This is a pre-activated Disney+ shared account (1-month).\nUpon successful payment, you will instantly receive the login credentials (Email, Password, and Profile Name/Number) via a unique retrieval link.\nDelivery Method: Login details are provided directly within your order page.\nEach customer should use their assigned profile and limit usage to one device at any time.',
    warranty_period: 'Same as your selected package (e.g., 1-month, 6-month).',
    warranty_method: 'Replacement of the account or a proportionate refund for the remaining subscription time if the account becomes inactive due to technical issues not caused by the user.\n\nWarranty Conditions:\n- Full refund within 7 days if a replacement cannot be provided.\n- After 7 days: Refund based on the unused remaining period.\n\nWarranty Will Not Apply In The Following Cases:\n- Any attempt by the customer to change the account password, email, or profile settings outside of their assigned profile.\n- Using the account to violate Disney+ terms, such as commercial use or unauthorized sharing beyond the terms of the shared plan.',
  },
  { 
    name: 'HBO Max', 
    category_name: 'Streaming', 
    image_url: '/products/hbomax.webp',
    info: 'A shared access account to the HBO Max (Max) service, providing access to all streaming content. All users share the same account login.\nFeatures requiring unique personal logins may not be fully supported on this shared model.\nUsers must not attempt to link or unlink any devices or change the account details. Violation leads to immediate loss of warranty. Only one stream per customer is allowed.',
    order_fulfillment: 'A pre-created HBO Max shared account (1-month) used collaboratively by multiple customers.\nYour account login (Email and Password) will be provided immediately after payment via a dedicated retrieval page.\nDelivery: Credentials are instantly accessible on your order completion page.\nLimit usage to one active stream per customer to ensure service quality for all users.',
    warranty_period: 'Same as your selected package (e.g., 1-month, 3-month).',
    warranty_method: 'Replacement with a functional equivalent account within 24 hours of reporting the issue, or a refund for the unused time.\n\nWarranty Conditions:\n- Full refund for account issues reported within the first 7 days, if irresolvable.\n- Beyond 7 days: Refund is prorated based on the number of unused days remaining on the subscription.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer attempts any unauthorized changes to the account\'s security settings or billing information.\n- Service disruption caused by the customer\'s specific geographic location not supported by the account\'s region.',
  },
  { 
    name: 'Amazon Prime Video', 
    category_name: 'Streaming', 
    image_url: '/products/primevideo.png',
    info: 'Shared access to the Amazon Prime Video component of an Amazon Prime account. This grants access to the Prime Video library.\n**Important:** This does NOT include other Amazon Prime benefits (e.g., free shipping, Prime Music, Kindle access).\nUsers are strictly forbidden from making purchases (rentals or buy) on the account or accessing any other Amazon services. Use is limited to Prime Video only.',
    order_fulfillment: 'You will receive the login details (Email and Password) for the Prime Video component of a shared Amazon account (1-month).\nCredentials are sent immediately after successful payment through a secure link.\nDelivery: Instant delivery on the post-purchase screen.\nCustomers must only access the Prime Video application or website and not the main Amazon shopping platform.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Account replacement or a refund calculated on the remaining duration if Prime Video access is lost due to technical fault.\n\nWarranty Conditions:\n- Full refund is available if service failure occurs within the first 7 days and a replacement is not possible.\n- After 7 days: Partial refund is issued based on the proportional unused time remaining.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer attempts to make any purchase (rental/buy) on the Amazon platform using the shared account.\n- The account is suspended due to attempts to change the security questions, email, or password.',
  },
  { 
    name: 'Hulu', 
    category_name: 'Streaming', 
    image_url: '/products/hulu.jpeg',
    info: 'A shared Hulu account, typically for the Ad-Free plan, allowing access to the full content library.\nDue to shared usage, features like Live TV or premium add-ons may not be included or supported.\nCustomers must use the service only on the assigned device slots and must not modify any profile or account settings. Violating device limits may lead to account suspension.',
    order_fulfillment: 'A pre-activated Hulu shared account (1-month) with login details (Email and Password) provided instantly after payment via a secure link.\nDelivery: Account credentials appear immediately after payment confirmation.\nUsage is restricted to the specific device slot assigned to you. Do not attempt to log in on multiple devices simultaneously.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Replacement of the shared account or a pro-rata refund for the remaining subscription period.\n\nWarranty Conditions:\n- If an issue cannot be resolved, a full refund applies if reported within 7 days of purchase.\n- After 7 days: A prorated refund is calculated for account issues reported after the initial 7-day period.\n\nWarranty Will Not Apply In The Following Cases:\n- Unauthorized attempts to change the account\'s associated email or password.\n- Account suspension resulting from exceeding the authorized number of simultaneous streams or device logins.',
  },
  { 
    name: 'Apple TV+', 
    category_name: 'Streaming', 
    image_url: '/products/appletv.png',
    info: 'Access to Apple TV+ content through a shared Apple ID or Family Sharing slot.\nThis is for Apple TV+ content only and does not include other Apple services (iCloud, Apple Music, etc.).\nUsers must ensure their device is logged in only for the TV app as instructed and must not access personal data/settings related to the shared Apple ID.',
    order_fulfillment: 'Shared Apple TV+ access (1-month). You will receive instructions on how to join the Family Sharing group or the shared Apple ID login details immediately after payment.\nDelivery: Instructions and/or credentials are provided on the order page.\nFollow the provided setup guide precisely to ensure seamless access without affecting other users.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Restoration of access (by re-adding to Family or providing new login) or a refund for the unused service time.\n\nWarranty Conditions:\n- A 100% refund of the order value is guaranteed for irresolvable issues within the first 7 days.\n- After 7 days: Refund is calculated based on the unused portion of the purchased period.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer intentionally removes themselves from the Family Sharing group or changes the shared Apple ID password.\n- Account suspension due to unauthorized access or modification of other shared Apple services (e.g., iCloud storage, purchases).',
  },
  { 
    name: 'YouTube Premium', 
    category_name: 'Streaming', 
    image_url: '/products/youtube.png',
    info: 'Premium access to YouTube (ad-free, background play, downloads) via a Family Group invitation.\nThis product provides access to your **personal Google/YouTube account** but under a shared payment/Family plan.\nTo maintain access, you must remain in the Family Group and not attempt to change the family administrator or move to a new family group prematurely.',
    order_fulfillment: 'YouTube Premium access (1-month) via a Family Invitation.\nAfter purchase, you will instantly receive a unique Family Invitation Link via email and the order page.\nDelivery: The invitation link is provided immediately.\nTo activate, click the link and accept the invitation to join the YouTube Family Group with your own Google account.',
    warranty_period: 'Same as your selected package (e.g., 1-month, 12-month).',
    warranty_method: 'Re-invitation to a new Family Group or a refund based on the remaining subscription time.\n\nWarranty Conditions:\n- Full refund if access is lost and cannot be restored within 7 days.\n- After 7 days: Refund is calculated proportionally based on the unused subscription period remaining.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer has already joined and left another YouTube Family Group within the last 12 months (a Google restriction).\n- The customer attempts to change the region or other settings of the Family Group, leading to loss of access.',
  },
  { 
    name: 'Steam Wallet', 
    category_name: 'Gaming Accounts', 
    image_url: '/products/steam.png',
    info: 'This is a digital code for adding funds to your personal Steam Wallet. The value is denominated in the currency specified at purchase.\nCodes are region-locked; ensure the purchased region matches your personal Steam account region.\nOnce the code is redeemed, the funds are non-refundable and subject to Steam\'s own Terms of Service.',
    order_fulfillment: 'A digital Steam Wallet Code of the selected denomination.\nUpon successful payment, the 15-digit code will be instantly displayed on your order page and sent to your email.\nDelivery: Instant display of the code.\nTo use, go to your Steam account, select "Account Details," and choose "Add Funds to your Steam Wallet."',
    warranty_period: 'Code Validity: Until redeemed. Product Warranty: 7 days.',
    warranty_method: 'Replacement of the code if it is proven to be invalid or already used upon first attempt at redemption.\n\nWarranty Conditions:\n- A full refund is provided if the code is invalid and a replacement cannot be sourced within 24 hours (within 7 days of purchase).\n\nWarranty Will Not Apply In The Following Cases:\n- The code has been successfully redeemed but the customer made a purchase mistake (e.g., wrong currency or game).\n- The customer provides incorrect region details, and the code is rejected by Steam due to region lock.',
  },
  { 
    name: 'Epic Games Wallet', 
    category_name: 'Gaming Accounts', 
    image_url: '/products/epicgames.png',
    info: 'A digital code to add currency to your Epic Games Wallet. The value is fixed and non-transferable.\nEnsure the region of the code is compatible with your Epic Games account.\nThis code can be used to purchase games or in-game content available on the Epic Games Store.',
    order_fulfillment: 'A digital Epic Games Wallet Code.\nImmediately after successful transaction, the unique redemption code will be presented on the confirmation screen and sent to your registered email address.\nDelivery: Instant display of the code.\nRedeem the code via the Epic Games Launcher or the Epic Games Store website under "Redeem Code."',
    warranty_period: 'Code Validity: Until redeemed. Product Warranty: 7 days.',
    warranty_method: 'Replacement of the digital code if it is verified as non-functional or previously redeemed prior to your use.\n\nWarranty Conditions:\n- A full, 100% refund is available if the code is faulty and a replacement cannot be given within the first 7 days.\n\nWarranty Will Not Apply In The Following Cases:\n- The code has been successfully redeemed and the funds added to the customer\'s wallet.\n- The customer loses the code or fails to redeem it within the warranty period, and the code is later used by a third party.',
  },
  { 
    name: 'Xbox Game Pass', 
    category_name: 'Gaming Accounts', 
    image_url: '/products/xbox.jpg',
    info: 'A digital code for a subscription to Xbox Game Pass (e.g., Ultimate or PC).\nCheck the code\'s specific tier and duration before purchase.\n**Important:** Ensure your Microsoft account is eligible for the redemption (e.g., no active conflicting subscriptions).\nCodes are non-refundable once redeemed.',
    order_fulfillment: 'A unique Xbox Game Pass digital code for the selected period (e.g., 1-month).\nUpon confirmation of payment, the code will be instantly delivered via a secure link on the order page.\nDelivery: Instant display of the code.\nTo redeem, visit the Microsoft/Xbox redemption site and enter the 25-character code.',
    warranty_period: 'Code Validity: Until redeemed. Product Warranty: 7 days.',
    warranty_method: 'Replacement of a non-functional or invalid code.\n\nWarranty Conditions:\n- 100% refund will be issued if the code is proven invalid on first redemption attempt and no replacement is available within 48 hours (within 7 days of purchase).\n\nWarranty Will Not Apply In The Following Cases:\n- The customer\'s Microsoft account is ineligible to redeem the code due to an existing, non-stackable subscription or regional conflict.\n- The code has been successfully redeemed but the customer decides they no longer want the service.',
  },
  { 
    name: 'PlayStation Plus', 
    category_name: 'Gaming Accounts', 
    image_url: '/products/psplus.jpg',
    info: 'A digital code for a PlayStation Plus subscription (e.g., Essential, Extra, or Premium).\nConfirm the region of the code matches your PlayStation Network (PSN) account region.\nThe code provides the subscription benefits for the specified duration, adding to any existing subscription up to the PSN limit.',
    order_fulfillment: 'A digital 12-digit code for a PlayStation Plus subscription (e.g., 1-month).\nAfter payment verification, the code will be immediately available on the order confirmation page and in your email.\nDelivery: Instant code delivery.\nRedeem the code on your PlayStation console or the PSN web store under "Redeem Codes."',
    warranty_period: 'Code Validity: Until redeemed. Product Warranty: 7 days.',
    warranty_method: 'Replacement of the purchased code if it is found to be invalid or previously used before its first attempted redemption by the customer.\n\nWarranty Conditions:\n- Full refund if the code is faulty and a resolution (replacement or fix) cannot be provided within 7 days of the purchase date.\n\nWarranty Will Not Apply In The Following Cases:\n- The code is rejected due to a mismatch between the code\'s region and the customer\'s PSN account region.\n- The customer loses or shares the code, and it is redeemed by an unauthorized party.',
  },
  { 
    name: 'GOG Wallet', 
    category_name: 'Gaming Accounts', 
    image_url: '/products/gog.png',
    info: 'A voucher code to add funds to your personal GOG (Good Old Games) Wallet.\nFunds added are typically non-refundable and can be used across the GOG platform for games and other content.\nEnsure the code is redeemed within the validity period, if any, stated by GOG or the provider.',
    order_fulfillment: 'A digital GOG Wallet voucher code.\nUpon successful completion of the purchase, the redemption code will be instantly accessible on the order fulfillment page.\nDelivery: Instant code delivery.\nRedeem the code via the GOG Galaxy client or the GOG website under "Redeem Code."',
    warranty_period: 'Code Validity: Until redeemed. Product Warranty: 7 days.',
    warranty_method: 'Replacement code provided if the original code is proven to be non-functional upon first use.\n\nWarranty Conditions:\n- 100% refund of the value if the code is invalid and a working replacement cannot be supplied within 7 days of purchase.\n\nWarranty Will Not Apply In The Following Cases:\n- The code is lost, forgotten, or not redeemed, and the wallet funds are claimed by another person.\n- The customer has successfully redeemed the code, and the value is reflected in their GOG Wallet.',
  },
  { 
    name: 'Origin Wallet', 
    category_name: 'Gaming Accounts', 
    image_url: '/products/origin.svg',
    info: 'A digital code to add funds to your personal EA/Origin Wallet (now part of the EA App ecosystem).\nThese funds are used for purchasing games, expansions, and in-game content on the EA platform.\nCodes are typically region-specific; please verify compatibility with your EA account region.',
    order_fulfillment: 'A digital Origin/EA Wallet Code of the selected value.\nPayment confirmation results in the immediate display of the code on your order summary page.\nDelivery: Instant code delivery.\nRedeem the code via the EA App or the EA website under "Redeem Product Code."',
    warranty_period: 'Code Validity: Until redeemed. Product Warranty: 7 days.',
    warranty_method: 'Replacement of the code if it is found to be invalid or already claimed at the time of your first attempt to redeem.\n\nWarranty Conditions:\n- A full refund if a faulty code cannot be replaced within 48 hours of reporting the issue (must be reported within 7 days of purchase).\n\nWarranty Will Not Apply In The Following Cases:\n- The customer provides the wrong region for their account, resulting in the code being rejected by EA\'s system.\n- The customer has redeemed the code but wishes to refund the wallet funds for personal reasons.',
  },
  { 
    name: 'Spotify Premium', 
    category_name: 'Music', 
    image_url: '/products/spotify.png',
    info: 'Premium access to Spotify (ad-free, high-quality streaming) via a Family Group invitation.\nThis is applied to your **personal Spotify account**.\nTo maintain the service, you must accept the Family invitation and ensure your account meets the geographical location requirements set by the Family administrator.',
    order_fulfillment: 'Spotify Premium access (1-month) via a Family Invitation Link.\nImmediately upon successful payment, you will receive the unique invitation link and instructions via the order confirmation page.\nDelivery: Instant link delivery.\nClick the link and confirm your address (if requested) to join the Spotify Family Group.',
    warranty_period: 'Same as your selected package (e.g., 1-month, 12-month).',
    warranty_method: 'Re-invitation to a new Family Group or a refund proportional to the unused remaining subscription time.\n\nWarranty Conditions:\n- 100% refund if access is lost and cannot be restored within 7 days of purchase.\n- After 7 days: A prorated refund is issued for service loss reported after the initial 7-day period.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer changes their location (as recorded by Spotify) causing them to be ineligible for the Family plan region.\n- The customer has recently left or changed Family Plans, violating Spotify\'s anti-abuse policies.',
  },
  { 
    name: 'Apple Music', 
    category_name: 'Music', 
    image_url: '/products/applemusic.jpg',
    info: 'Premium access to Apple Music via a Family Sharing slot.\nThis product grants the full Apple Music benefit on your personal Apple ID.\nTo ensure continued service, you must remain in the Family Sharing group for the duration of your purchase.',
    order_fulfillment: 'Apple Music Family Sharing slot (1-month).\nImmediately after payment, you will receive the Family Invitation link/instructions via the order page and email.\nDelivery: Instant delivery of the invitation details.\nAccept the invitation with your personal Apple ID to gain Apple Music Premium access.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Re-invitation or a refund calculated on the unused remaining time.\n\nWarranty Conditions:\n- Full refund if access is lost and cannot be restored within 7 days.\n- After 7 days: Refund is calculated based on the unused portion of the purchased period.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer intentionally leaves the Family Sharing group before the subscription period ends.\n- Loss of access due to the customer\'s Apple ID violating Apple\'s terms of service.',
  },
  { 
    name: 'Tidal HiFi', 
    category_name: 'Music', 
    image_url: '/products/tidal.jpg',
    info: 'Access to Tidal HiFi or HiFi Plus via a shared account or Family Plan slot.\nIf shared, each user is assigned a specific profile for managing playlists and listening history.\nUsers must not change the account\'s primary login details (email/password).',
    order_fulfillment: 'Tidal HiFi shared access (1-month).\nAccount login details or a Family invitation link are provided instantly after payment via a secure retrieval link.\nDelivery: Instant delivery of credentials/link.\nUse the service on your designated profile or via the accepted family invitation.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Replacement of the shared account/Family invitation or a proportional refund for the remaining subscription period.\n\nWarranty Conditions:\n- 100% refund for irresolvable issues reported within the first 7 days.\n- Refund is prorated based on the unused subscription time after the initial 7-day period.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer attempts to modify the primary account login details or payment information.\n- Account suspension due to abuse of simultaneous stream limits.',
  },
  { 
    name: 'Deezer Premium', 
    category_name: 'Music', 
    image_url: '/products/deezer.png',
    info: 'Premium access to Deezer, typically via a Family/Shared account model.\nEach user is assigned a specific, non-transferable profile.\nEnsure you use only the designated profile and do not attempt to create or delete profiles or change the main account settings.',
    order_fulfillment: 'Deezer Premium shared account (1-month).\nLogin details (Email, Password, and Profile name) are provided instantly upon successful payment via a retrieval link.\nDelivery: Instant access to credentials on the order page.\nLimit usage to your assigned profile and one device at a time.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Replacement of the account/profile or a partial refund corresponding to the unused time.\n\nWarranty Conditions:\n- Full refund if a replacement cannot be provided for a non-functional service within 7 days of purchase.\n- After 7 days: The refund is calculated proportionally to the remaining service time.\n\nWarranty Will Not Apply In The Following Cases:\n- Any attempts to change the main account\'s email, password, or to delete other user profiles.\n- The account is blocked by Deezer due to excessive simultaneous streaming from the customer\'s end.',
  },
  { 
    name: 'Microsoft Office 365', 
    category_name: 'Software Licenses', 
    image_url: '/products/office365.avif',
    info: 'A license key or shared Microsoft 365 Family/Personal subscription slot.\nIf a key, it activates the software for the specified duration (e.g., 1 year). If a shared slot, it provides access to the suite using your personal Microsoft account.\n**Important:** For shared access, do not attempt to manage or view other users\' files or data. Some features like Copilot may be restricted to the subscription owner.',
    order_fulfillment: 'Microsoft Office 365 license key or Family Sharing Invitation.\nDelivery is instant upon payment confirmation via a secure product retrieval page.\nDelivery: Instant key/link delivery.\nIf a key, redeem it on the official Microsoft redemption portal. If an invitation, accept it with your Microsoft account.',
    warranty_period: 'Same as your selected package (e.g., 1-year).',
    warranty_method: 'Replacement of the non-functional key/invitation or a refund based on the remaining license/subscription period.\n\nWarranty Conditions:\n- A 100% refund is guaranteed if a purchased key is invalid and cannot be replaced within 48 hours (within 7 days of purchase).\n- For shared access, a prorated refund is issued if access is lost and cannot be restored after 7 days.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer\'s device or operating system does not meet the minimum requirements for Microsoft 365.\n- The customer violates the terms of the Family/Shared plan (e.g., attempting to change the administrator\'s settings).',
  },
  { 
    name: 'Windows 10 Pro', 
    category_name: 'Software Licenses', 
    image_url: '/products/windows10.png',
    info: 'A genuine, single-use digital product key (OEM or Retail) for activating Windows 10 Pro.\nThe key is valid for one activation on one computer only.\nCustomers are responsible for having the correct edition (Pro) and a clean installation of Windows 10 before attempting activation.',
    order_fulfillment: 'A unique 25-character Windows 10 Pro product key.\nUpon successful payment, the key will be immediately displayed on the order confirmation page.\nDelivery: Instant key delivery.\nEnter the key into the Windows Activation settings on your PC to activate the operating system.',
    warranty_period: 'Lifetime Activation (subject to Microsoft terms). Product Warranty: 30 days.',
    warranty_method: 'Replacement of the key if it fails to activate on a valid installation (a clean, eligible device) or a full refund.\n\nWarranty Conditions:\n- Full refund if the key is proven to be invalid or blocked by Microsoft upon first use, and a replacement cannot be provided within 48 hours (within 30 days of purchase).\n\nWarranty Will Not Apply In The Following Cases:\n- Activation failure due to the customer\'s existing hardware/software configuration or the attempt to activate on an ineligible Windows edition (e.g., Home).\n- The key is successfully activated, but the customer later changes hardware, invalidating the OEM key.',
  },
  { 
    name: 'Adobe Photoshop', 
    category_name: 'Software Licenses', 
    image_url: '/products/photoshop.png',
    info: 'Access to Adobe Photoshop (and often the Creative Cloud) via a shared educational/team account or an individual license key.\nIf a shared account, users are assigned a personal cloud storage and project space.\n**Warning:** Do not attempt to use the shared account for commercial projects that violate the educational/team license terms.',
    order_fulfillment: 'Adobe Photoshop access (1-month) via a team invitation or shared account details.\nImmediately after payment, you will receive the team invitation link or login credentials.\nDelivery: Instant access to link/credentials.\nFollow the provided instructions to log in and download/activate Photoshop on your device.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Re-invitation or replacement of the account/login if access is revoked due to a non-user-caused fault, or a proportional refund.\n\nWarranty Conditions:\n- 100% refund if access is lost and cannot be restored within 7 days.\n- Refund is prorated based on the unused subscription time after 7 days.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer attempts to modify the shared account\'s email, password, or primary plan settings.\n- Account suspension due to violating Adobe\'s terms of service (e.g., using the account for illegal activities).',
  },
  { 
    name: 'Adobe Illustrator', 
    category_name: 'Software Licenses', 
    image_url: '/products/illustrator.avif',
    info: 'Access to Adobe Illustrator, typically provided through a Creative Cloud Team or Shared account.\nProvides full desktop and cloud features of Illustrator.\nUsers must not attempt to use or view the cloud storage of other shared users.',
    order_fulfillment: 'Adobe Illustrator access (1-month) via a team invitation.\nInstant delivery of the invitation link and instructions after successful payment.\nDelivery: Instant link delivery.\nAccept the invitation with your Adobe ID to gain access to Illustrator within the Creative Cloud suite.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Restoration of access via re-invitation or a proportional refund for the remaining license period.\n\nWarranty Conditions:\n- Full refund if access is lost and cannot be restored within 7 days of purchase.\n- Refund is calculated based on the unused remaining time after the first 7 days.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer is found to be sharing the provided access with third parties.\n- The customer modifies their Adobe ID details that were used for the shared access, causing the license to fail.',
  },
  { 
    name: 'Final Cut Pro', 
    category_name: 'Software Licenses', 
    image_url: '/products/finalcut.webp',
    info: 'A pre-activated license for Final Cut Pro, often provided via a volume license or shared App Store account.\nThis grants full, unlimited access to the software on a single macOS device.\n**Crucial:** Users must not update the application in a way that risks losing the shared/volume license key.',
    order_fulfillment: 'Final Cut Pro pre-activated license details or an App Store account login (1-time purchase).\nLogin details/instructions are provided instantly after payment via a secure retrieval link.\nDelivery: Instant access to credentials/instructions.\nFollow the activation guide precisely to install and use the software without issue.',
    warranty_period: 'Lifetime Activation (subject to Apple terms). Product Warranty: 30 days.',
    warranty_method: 'Replacement of the license/account or a full refund if the license fails to activate or is revoked due to a seller fault.\n\nWarranty Conditions:\n- Full refund if the provided key/account is non-functional or revoked within 30 days of activation.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer attempts to transfer the license to a different macOS device without authorization.\n- Loss of access due to an OS update that voids the specific license type (e.g., volume license) when the customer was warned against the update.',
  },
  { 
    name: 'Premiere Pro', 
    category_name: 'Software Licenses', 
    image_url: '/products/premiere.png',
    info: 'Access to Adobe Premiere Pro via a Creative Cloud Team or Shared account model.\nAllows full use of the video editing software.\nUsers must adhere to the terms of the shared account and avoid modifications to the primary Adobe ID.',
    order_fulfillment: 'Adobe Premiere Pro access (1-month) via a team invitation.\nInstant delivery of the invitation link and instructions after successful payment.\nDelivery: Instant link delivery.\nAccept the invitation with your Adobe ID to gain access to Premiere Pro within the Creative Cloud suite.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Restoration of access via re-invitation or a proportional refund for the remaining license period.\n\nWarranty Conditions:\n- Full refund if access is lost and cannot be restored within 7 days of purchase.\n- Refund is calculated based on the unused remaining time after the first 7 days.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer is found to be sharing the provided access with third parties.\n- The customer modifies their Adobe ID details that were used for the shared access, causing the license to fail.',
  },
  { 
    name: 'NordVPN', 
    category_name: 'VPN Services', 
    image_url: '/products/nordvpn.webp',
    info: 'Access to NordVPN services via a shared account login.\nThis account may support multiple simultaneous connections, but usage must be reasonable and non-abusive.\n**Prohibited Activity:** Do not change the primary email or password, or use the service for illegal activities (e.g., copyright infringement, spamming, bulk usage). Violation will result in immediate warranty denial and account loss.',
    order_fulfillment: 'NordVPN shared account login (Email and Password) for the selected duration (e.g., 1-month).\nCredentials are provided instantly after payment via a secure retrieval link.\nDelivery: Instant access to credentials on the order page.\nCustomers can use the shared account on the maximum number of devices supported by the plan, provided the usage is for personal, non-commercial purposes.',
    warranty_period: 'Same as your selected package (e.g., 1-month, 1-year).',
    warranty_method: 'Replacement of the shared account or a proportional refund for the unused subscription time.\n\nWarranty Conditions:\n- 100% refund if the account stops working and cannot be replaced within 48 hours (within 7 days of purchase).\n- After 7 days: Refund is prorated based on the remaining days of the purchased period.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer changes the account email, password, or attempts to access billing information.\n- Account suspension due to excessive or abusive bandwidth usage, or use for illegal activities (e.g., botting, spamming).',
  },
  { 
    name: 'ExpressVPN', 
    category_name: 'VPN Services', 
    image_url: '/products/expressvpn.jpg',
    info: 'Access to ExpressVPN via a shared account login.\nEach shared account has a limit on simultaneous connections. Users must manage their device usage responsibly.\n**Prohibited Activity:** Sharing the account beyond the agreed-upon single-user/household limit, or using the service for unauthorized or illegal activities. Changing login details will void the warranty.',
    order_fulfillment: 'ExpressVPN shared account login (Email and Password) for the selected duration (e.g., 1-month).\nLogin details are delivered instantly upon payment confirmation via a secure retrieval link.\nDelivery: Instant access to credentials on the order page.\nAccess is for one customer, limited to the single-user terms of the shared account, though simultaneous connections may be possible on a personal basis.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Account replacement or a refund proportional to the unused duration if the account becomes non-functional due to provider error.\n\nWarranty Conditions:\n- Full refund within 7 days if the service is lost and cannot be restored.\n- After 7 days: Refund is prorated based on the remaining subscription time.\n\nWarranty Will Not Apply In The Following Cases:\n- Any attempt to modify the account credentials, including the password or recovery details.\n- Suspension of service due to customer violation of ExpressVPN\'s Acceptable Use Policy (AUP).',
  },
  { 
    name: 'Surfshark', 
    category_name: 'VPN Services', 
    image_url: '/products/surfshark.jpg',
    info: 'Access to Surfshark VPN via a shared account login.\nSurfshark typically allows unlimited devices per account; however, this shared account is intended for single-user, personal use.\nUsers are forbidden from sharing the login with external parties or altering the account details.',
    order_fulfillment: 'Surfshark shared account login (Email and Password) for the selected duration (e.g., 1-month).\nCredentials will be instantly displayed on your order completion page.\nDelivery: Instant access to credentials.\nUse the provided login to connect to the VPN on your personal devices.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Replacement account or a proportional refund for the remaining subscription period.\n\nWarranty Conditions:\n- 100% refund if the account is non-functional upon first use and a replacement is not available within 24 hours (within 7 days of purchase).\n- After 7 days: Refund is calculated based on the proportional unused time remaining.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer shares the account login with individuals outside their immediate use, leading to an account block.\n- The customer attempts to contact Surfshark support for account changes or billing issues, revealing the shared nature of the account.',
  },
  { 
    name: 'VPN Unlimited', 
    category_name: 'VPN Services', 
    image_url: '/products/vpnunlimited.webp',
    info: 'Access to VPN Unlimited via a shared account login.\nEach plan limits the number of connected devices; users must respect the shared device limit.\nChanging the account password or using the VPN for prohibited file-sharing (P2P) in restricted servers will void the warranty.',
    order_fulfillment: 'VPN Unlimited shared account login (Email and Password) for the selected duration (e.g., 1-month).\nLogin details are instantly delivered after payment via a secure link.\nDelivery: Instant access to credentials.\nLog in and manage your connected devices within the allowed limit of the shared plan.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Account replacement or a proportional refund for the remaining subscription time.\n\nWarranty Conditions:\n- Full refund if the account is immediately revoked and a replacement cannot be provided within 48 hours (within 7 days of purchase).\n- After 7 days: Refund is prorated based on the number of unused days remaining.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer exceeds the allocated device limit, causing an account lockout.\n- Use of the VPN service for illegal activities or in a manner that violates the provider\'s terms of service.',
  },
  { 
    name: 'Dropbox Premium', 
    category_name: 'Cloud Storage', 
    image_url: '/products/dropbox.png',
    info: 'Access to a shared Dropbox Professional/Team plan, providing the user with a designated storage space (e.g., 1TB).\nYour files are private to your user slot and cannot be accessed by other users on the shared account.\nUsers must not modify the shared plan settings, invite new members, or attempt to change the administrator\'s details.',
    order_fulfillment: 'Dropbox Team/Professional slot access (1-month).\nYou will receive an invitation link to join the shared Dropbox Team/Business account immediately after purchase.\nDelivery: Instant invitation link delivery.\nAccept the invitation with your personal Dropbox account to receive the storage upgrade.',
    warranty_period: 'Same as your selected package (e.g., 1-month, 1-year).',
    warranty_method: 'Re-invitation to the team/plan or a refund proportional to the unused remaining subscription time.\n\nWarranty Conditions:\n- 100% refund if access is lost and cannot be restored within 7 days of purchase.\n- After 7 days: Refund is calculated proportionally based on the unused subscription period remaining.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer leaves the team/plan intentionally or is removed due to violation of the shared account terms (e.g., attempting administrative actions).\n- File deletion or loss is not covered; the customer is responsible for managing their data.',
  },
  { 
    name: 'Google One', 
    category_name: 'Cloud Storage', 
    image_url: '/products/googleone.png',
    info: 'Access to a shared Google One Family plan, providing the user with access to the shared storage pool and benefits (e.g., VPN, expert support).\nYour files remain private within your personal Google account. Only the total shared storage is pooled.\nUsers must reside in the same country as the family manager and cannot attempt to take over the manager role.',
    order_fulfillment: 'Google One Family plan invitation (1-month).\nAfter purchase, you will receive an invitation link to join the Google Family Group immediately.\nDelivery: Instant invitation link delivery.\nAccept the invitation with your personal Google account to gain access to the shared storage and benefits.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Re-invitation to the Family Group or a proportional refund for the unused subscription time.\n\nWarranty Conditions:\n- Full refund if access is lost and cannot be restored within 7 days.\n- After 7 days: Refund is calculated based on the proportional unused time remaining.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer is unable to join the Family Group due to already being in one or due to the 12-month cool-down period imposed by Google.\n- The customer violates Google\'s policies, leading to the suspension of their personal account and loss of access.',
  },
  { 
    name: 'OneDrive Premium', 
    category_name: 'Cloud Storage', 
    image_url: '/products/onedrive.jpg',
    info: 'Access to a shared Microsoft 365 Family plan slot, providing the user with 1TB of dedicated OneDrive storage and premium features.\nYour storage space is personal and private, separate from other users on the plan.\nUsers must not attempt to modify the family plan settings, which could result in revocation of their 1TB access.',
    order_fulfillment: 'Microsoft 365 Family Sharing Invitation (1-month).\nYou will receive a link to join the shared Microsoft Family subscription immediately after payment.\nDelivery: Instant invitation link delivery.\nAccept the invitation with your personal Microsoft account to activate the 1TB OneDrive storage.',
    warranty_period: 'Same as your selected package (e.g., 1-month, 1-year).',
    warranty_method: 'Re-invitation to the Family plan or a proportional refund for the unused subscription time.\n\nWarranty Conditions:\n- 100% refund if the 1TB storage access is lost and cannot be restored within 7 days.\n- After 7 days: Refund is prorated based on the remaining subscription time.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer attempts to manage the Family plan or changes their Microsoft account details in a way that interferes with the shared subscription.\n- The customer uses the storage to host illegal content, leading to account suspension by Microsoft.',
  },
  { 
    name: 'iCloud Storage', 
    category_name: 'Cloud Storage', 
    image_url: '/products/icloud.jpg',
    info: 'Access to a shared iCloud+ Family Sharing plan, which pools the total storage capacity (e.g., 2TB) among family members.\nYour photos, documents, and backups remain private to your Apple ID; only the storage limit is shared.\nUsers must remain in the Family Sharing group and must not attempt to upgrade or downgrade the primary plan themselves.',
    order_fulfillment: 'iCloud+ Family Sharing invitation (1-month).\nInstructions and an invitation link to join the Apple Family Sharing group will be provided instantly after payment.\nDelivery: Instant access to the invitation link.\nAccept the invitation with your personal Apple ID to start using the shared storage pool.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Restoration of Family Sharing access or a proportional refund for the unused subscription time.\n\nWarranty Conditions:\n- Full refund if the shared storage access is lost and cannot be restored within 7 days.\n- After 7 days: Refund is calculated proportionally based on the unused subscription period remaining.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer leaves the Family Sharing group intentionally.\n- The customer uses the shared account for purposes that violate Apple\'s iCloud+ terms of service.',
  },
  { 
    name: 'Coursera Plus', 
    category_name: 'E-Learning Platforms', 
    image_url: '/products/coursera.png',
    info: 'Access to Coursera Plus via a shared institutional/team account or pre-activated access.\nThis grants unlimited access to most courses and specializations.\nCustomers must use the service only for personal learning and are forbidden from accessing or modifying any administrative sections of the institutional account.',
    order_fulfillment: 'Coursera Plus access (1-month) via a shared institutional account login or invitation.\nLogin details or an invitation link are provided instantly after payment via a secure retrieval link.\nDelivery: Instant access to credentials/link.\nLog in to Coursera to enroll in courses under the Plus subscription.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Replacement of the account/re-invitation or a refund proportional to the unused subscription time.\n\nWarranty Conditions:\n- 100% refund if access is lost and cannot be restored within 7 days of purchase.\n- After 7 days: Refund is prorated based on the remaining subscription time.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer violates Coursera\'s Honor Code or attempts to use the institutional account for commercial gain.\n- The customer modifies the primary account\'s email or password.',
  },
  { 
    name: 'Skillshare Premium', 
    category_name: 'E-Learning Platforms', 
    image_url: '/products/skillshare.png',
    info: 'Access to Skillshare Premium via a shared team or organizational account.\nAllows unlimited viewing of all premium classes.\nUsers must not attempt to use or view the profiles, projects, or billing information of other shared members.',
    order_fulfillment: 'Skillshare Premium access (1-month) via a team invitation or shared login.\nLogin details or an invitation link are provided instantly after payment via a secure retrieval link.\nDelivery: Instant access to credentials/link.\nUse the provided access to start watching premium classes on Skillshare.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Replacement of the account/profile or a partial refund corresponding to the unused time.\n\nWarranty Conditions:\n- Full refund if access is lost and cannot be restored within 7 days.\n- After 7 days: Refund is calculated proportionally to the remaining service time.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer shares the provided access with individuals outside the single-user arrangement.\n- The customer attempts unauthorized access or modification of the shared account\'s details.',
  },
  { 
    name: 'Udemy Pro', 
    category_name: 'E-Learning Platforms', 
    image_url: '/products/udemy.png',
    info: 'Access to a selection of courses via a shared Udemy Business/Pro account.\nThis grants access to the curated collection of courses available under the business subscription.\nUsers must use the service only for professional development and are forbidden from administrative actions on the shared account.',
    order_fulfillment: 'Udemy Business/Pro access (1-month) via an invitation to join the organization\'s team.\nAn invitation link will be delivered instantly after payment.\nDelivery: Instant invitation link delivery.\nAccept the invitation with your personal Udemy account (or a new account) to start course enrollment.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Re-invitation to the organization or a proportional refund for the unused subscription time.\n\nWarranty Conditions:\n- 100% refund if access is lost and cannot be restored within 7 days.\n- After 7 days: Refund is calculated proportionally based on the unused subscription period remaining.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer leaves the organization\'s team intentionally.\n- Access is lost due to the customer\'s personal account being suspended for violating Udemy\'s terms.',
  },
  { 
    name: 'LinkedIn Learning', 
    category_name: 'E-Learning Platforms', 
    image_url: '/products/linkedin.png',
    info: 'Access to LinkedIn Learning Premium via a shared organizational license.\nThis provides unlimited access to the entire video library and learning paths.\nUsers must not attempt to change or view any information related to the shared organizational license or other team members.',
    order_fulfillment: 'LinkedIn Learning access (1-month) via a team invitation.\nAn invitation link to join the organization\'s learning group will be provided instantly after payment.\nDelivery: Instant invitation link delivery.\nAccept the invitation with your personal LinkedIn account to activate the premium features.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Re-invitation to the organizational team or a proportional refund for the unused subscription time.\n\nWarranty Conditions:\n- Full refund if access is lost and cannot be restored within 7 days.\n- After 7 days: Refund is calculated proportionally based on the unused subscription period remaining.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer is removed from the organization\'s group for attempting unauthorized access or administrative actions.\n- The customer violates LinkedIn\'s professional community policies, leading to account suspension.',
  },
  { 
    name: 'Canva Pro', 
    category_name: 'Design Tools', 
    image_url: '/products/canva.jpg',
    info: 'Access to Canva Pro via a shared team or organizational account.\nThis unlocks all Pro features, including premium templates, stock content, and Brand Kit (for the user\'s personal space).\nUsers must not attempt to modify the team settings or access designs belonging to other shared members.',
    order_fulfillment: 'Canva Pro access (1-month) via a team invitation link.\nAn invitation link to join the Canva Pro team will be provided instantly after payment.\nDelivery: Instant invitation link delivery.\nAccept the invitation with your personal Canva account to gain Pro access.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Re-invitation to the team or a proportional refund for the unused subscription time.\n\nWarranty Conditions:\n- 100% refund if access is lost and cannot be restored within 7 days.\n- After 7 days: Refund is calculated proportionally based on the unused subscription period remaining.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer attempts to change the team name, billing, or administrative settings, leading to removal from the team.\n- Loss of access due to the customer violating Canva\'s terms of service.',
  },
  { 
    name: 'Figma Professional', 
    category_name: 'Design Tools', 
    image_url: '/products/figma.webp',
    info: 'Access to Figma Professional via a shared organizational/educational team account.\nGrants full access to professional features, including unlimited files and team libraries.\nUsers are forbidden from viewing or modifying projects outside their designated team space and must not attempt administrative changes.',
    order_fulfillment: 'Figma Professional access (1-month) via a team invitation link.\nAn invitation link to join the shared Figma team will be provided instantly after payment.\nDelivery: Instant invitation link delivery.\nAccept the invitation with your personal Figma account to join the Pro team.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Re-invitation to the team or a proportional refund for the unused subscription time.\n\nWarranty Conditions:\n- Full refund if access is lost and cannot be restored within 7 days.\n- After 7 days: Refund is calculated proportionally based on the unused subscription period remaining.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer is removed from the team for attempting administrative actions or accessing unauthorized files.\n- The customer violates Figma\'s community guidelines, leading to account suspension.',
  },
  { 
    name: 'Sketch', 
    category_name: 'Design Tools', 
    image_url: '/products/sketch.png',
    info: 'A licensed key or a pre-activated account for Sketch on macOS.\nThis grants access to the full, non-subscription version of the Sketch application for the duration of the license/access.\nUsers must not attempt to use the key or login on more than one device simultaneously, or share the key externally.',
    order_fulfillment: 'Sketch license key or account login (1-month access).\nLogin details or a license key are provided instantly after payment via a secure retrieval link.\nDelivery: Instant access to credentials/key.\nUse the provided information to activate or log into the Sketch application on your single macOS device.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Replacement of the key/account or a partial refund corresponding to the unused time.\n\nWarranty Conditions:\n- 100% refund if the key/account is non-functional upon first use and a replacement cannot be provided within 48 hours (within 7 days of purchase).\n- After 7 days: Refund is prorated based on the remaining subscription time.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer attempts to use the license/account on multiple devices simultaneously.\n- The customer updates the application to a version that is incompatible with the provided license, despite warnings.',
  },
  { 
    name: 'Notion Premium', 
    category_name: 'Productivity Apps', 
    image_url: '/products/notion.png',
    info: 'Access to Notion Plus or Business via a shared workspace/team account.\nThis removes the block limit and grants access to premium features like Admin tools and version history (for the user\'s personal pages).\nUsers must not attempt to manage the shared workspace\'s billing or member list.',
    order_fulfillment: 'Notion Premium access (1-month) via a workspace invitation.\nAn invitation link to join the Notion team workspace will be provided instantly after payment.\nDelivery: Instant invitation link delivery.\nAccept the invitation with your personal Notion account to gain Premium access within the shared workspace.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Re-invitation to the workspace or a proportional refund for the unused subscription time.\n\nWarranty Conditions:\n- Full refund if access is lost and cannot be restored within 7 days.\n- After 7 days: Refund is calculated proportionally based on the unused subscription period remaining.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer violates Notion\'s acceptable use policy or attempts to modify the primary workspace administrator\'s settings.\n- The customer intentionally leaves the shared workspace.',
  },
  { 
    name: 'Todoist Premium', 
    category_name: 'Productivity Apps', 
    image_url: '/products/todoist.png',
    info: 'Access to Todoist Pro or Business via a shared team account.\nThis unlocks features like reminders, filters, labels, and project templates for the user\'s personal tasks.\nUsers must not attempt to view or modify projects or tasks belonging to other shared members.',
    order_fulfillment: 'Todoist Premium access (1-month) via a team invitation link.\nAn invitation link to join the shared Todoist Business team will be provided instantly after payment.\nDelivery: Instant invitation link delivery.\nAccept the invitation with your personal Todoist account to upgrade to Premium status.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Re-invitation to the team or a proportional refund for the unused subscription time.\n\nWarranty Conditions:\n- 100% refund if access is lost and cannot be restored within 7 days.\n- After 7 days: Refund is calculated proportionally based on the unused subscription period remaining.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer attempts to perform administrative actions on the shared team account.\n- The customer is removed from the team for violating Todoist\'s terms of use.',
  },
  { 
    name: 'Evernote Premium', 
    category_name: 'Productivity Apps', 
    image_url: '/products/evernote.png',
    info: 'Access to Evernote Personal/Professional via a shared team or organizational account.\nThis increases note size limits, enables syncing across unlimited devices, and adds search capabilities within PDFs.\nUsers must not attempt to view or modify notes or notebooks belonging to other shared members.',
    order_fulfillment: 'Evernote Premium access (1-month) via a team invitation.\nAn invitation link to join the shared Evernote team will be provided instantly after payment.\nDelivery: Instant invitation link delivery.\nAccept the invitation with your personal Evernote account to gain Premium access.',
    warranty_period: 'Same as your selected package (e.g., 1-month).',
    warranty_method: 'Re-invitation to the team or a proportional refund for the unused subscription time.\n\nWarranty Conditions:\n- Full refund if access is lost and cannot be restored within 7 days.\n- After 7 days: Refund is calculated proportionally based on the unused subscription period remaining.\n\nWarranty Will Not Apply In The Following Cases:\n- The customer attempts to perform unauthorized administrative actions on the team account.\n- The customer violates Evernote\'s terms of service, leading to their removal from the shared account.',
  },
];

export const comments = [
  { user_id: 1, product_id: 1, content: 'Great quality account, works perfectly!' },
  { user_id: 2, product_id: 1, content: 'Fast delivery and easy to use.' },
  { user_id: 3, product_id: 2, content: 'The subscription lasted as promised, very satisfied.' },
  { user_id: 4, product_id: 3, content: 'Good value for money, will buy again.' },
  { user_id: 2, product_id: 2, content: 'The account was activated quickly and without issues.' }
]

export const responses = [
  { comment_id: 1, answerer: 5, content: 'Thank you for your feedback! We\'re glad you\'re satisfied with the account.' },
  { comment_id: 3, answerer: 5, content: 'We appreciate your review! Looking forward to serving you again.' },
]
// ------------------- PRODUCT TYPES IN VND -------------------

export const productTypes = [
  // Netflix
  { product_name: 'Netflix Premium', type: '1 Month', original_price: 312000, discount_price: 240000, stock: 50 },
  { product_name: 'Netflix Premium', type: '3 Months', original_price: 888000, discount_price: 720000, stock: 30 },
  { product_name: 'Netflix Premium', type: '6 Months', original_price: 1776000, discount_price: 1440000, stock: 20 },

  // Disney+
  { product_name: 'Disney+ Account', type: '1 Month', original_price: 264000, discount_price: 216000, stock: 40 },
  { product_name: 'Disney+ Account', type: '3 Months', original_price: 792000, discount_price: 648000, stock: 25 },

  // HBO Max
  { product_name: 'HBO Max', type: '1 Month', original_price: 360000, discount_price: 312000, stock: 45 },

  // Amazon Prime
  { product_name: 'Amazon Prime Video', type: '1 Month', original_price: 360000, discount_price: 312000, stock: 35 },

  // Hulu
  { product_name: 'Hulu', type: '1 Month', original_price: 312000, discount_price: 240000, stock: 50 },

  // Apple TV+
  { product_name: 'Apple TV+', type: '1 Month', original_price: 240000, discount_price: 192000, stock: 40 },

  // YouTube Premium
  { product_name: 'YouTube Premium', type: '1 Month', original_price: 312000, discount_price: 264000, stock: 60 },

  // Gaming Wallets
  { product_name: 'Steam Wallet', type: '$50', original_price: 1200000, discount_price: 1080000, stock: 30 },
  { product_name: 'Steam Wallet', type: '$100', original_price: 2400000, discount_price: 2160000, stock: 20 },
  { product_name: 'Epic Games Wallet', type: '$50', original_price: 1200000, discount_price: 1128000, stock: 25 },
  { product_name: 'Xbox Game Pass', type: '1 Month', original_price: 360000, discount_price: 312000, stock: 40 },
  { product_name: 'PlayStation Plus', type: '1 Month', original_price: 360000, discount_price: 312000, stock: 40 },
  { product_name: 'GOG Wallet', type: '$50', original_price: 1200000, discount_price: 1080000, stock: 25 },
  { product_name: 'Origin Wallet', type: '$50', original_price: 1200000, discount_price: 1080000, stock: 25 },

  // Music
  { product_name: 'Spotify Premium', type: '1 Month', original_price: 240000, discount_price: 192000, stock: 50 },
  { product_name: 'Apple Music', type: '1 Month', original_price: 240000, discount_price: 192000, stock: 45 },
  { product_name: 'Tidal HiFi', type: '1 Month', original_price: 480000, discount_price: 360000, stock: 30 },
  { product_name: 'Deezer Premium', type: '1 Month', original_price: 264000, discount_price: 216000, stock: 40 },

  // Software Licenses
  { product_name: 'Microsoft Office 365', type: '1 Year', original_price: 2400000, discount_price: 1920000, stock: 25 },
  { product_name: 'Windows 10 Pro', type: '1 License', original_price: 3360000, discount_price: 2880000, stock: 15 },
  { product_name: 'Adobe Photoshop', type: '1 Year', original_price: 5760000, discount_price: 4800000, stock: 20 },
  { product_name: 'Adobe Illustrator', type: '1 Year', original_price: 5760000, discount_price: 4800000, stock: 20 },
  { product_name: 'Final Cut Pro', type: '1 License', original_price: 7199760, discount_price: 5999760, stock: 10 },
  { product_name: 'Premiere Pro', type: '1 Year', original_price: 5760000, discount_price: 4800000, stock: 20 },

  // VPN
  { product_name: 'NordVPN', type: '1 Year', original_price: 2879760, discount_price: 2159760, stock: 40 },
  { product_name: 'ExpressVPN', type: '1 Year', original_price: 2879760, discount_price: 2159760, stock: 35 },
  { product_name: 'Surfshark', type: '1 Year', original_price: 2159760, discount_price: 1727760, stock: 50 },
  { product_name: 'VPN Unlimited', type: '1 Month', original_price: 215760, discount_price: 167760, stock: 60 },

  // Cloud Storage
  { product_name: 'Dropbox Premium', type: '1 Month', original_price: 240000, discount_price: 192000, stock: 45 },
  { product_name: 'Google One', type: '1 Year', original_price: 2400000, discount_price: 1920000, stock: 40 },
  { product_name: 'OneDrive Premium', type: '1 Year', original_price: 2400000, discount_price: 1920000, stock: 35 },
  { product_name: 'iCloud Storage', type: '1 Year', original_price: 2400000, discount_price: 1920000, stock: 35 },

  // E-Learning
  { product_name: 'Coursera Plus', type: '1 Year', original_price: 9576000, discount_price: 7176000, stock: 20 },
  { product_name: 'Skillshare Premium', type: '1 Month', original_price: 360000, discount_price: 288000, stock: 50 },
  { product_name: 'Udemy Pro', type: '1 Year', original_price: 2400000, discount_price: 1920000, stock: 40 },
  { product_name: 'LinkedIn Learning', type: '1 Year', original_price: 2880000, discount_price: 2400000, stock: 30 },

  // Design Tools
  { product_name: 'Canva Pro', type: '1 Year', original_price: 1200000, discount_price: 960000, stock: 50 },
  { product_name: 'Figma Professional', type: '1 Year', original_price: 1440000, discount_price: 1200000, stock: 45 },
  { product_name: 'Sketch', type: '1 License', original_price: 720000, discount_price: 600000, stock: 35 },

  // Productivity Apps
  { product_name: 'Notion Premium', type: '1 Year', original_price: 480000, discount_price: 360000, stock: 60 },
  { product_name: 'Todoist Premium', type: '1 Year', original_price: 360000, discount_price: 288000, stock: 55 },
  { product_name: 'Evernote Premium', type: '1 Year', original_price: 480000, discount_price: 360000, stock: 45 },
];
